#
# Ref:
#   https://prometheus.io/docs/prometheus/latest/configuration/configuration
#   https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config
#   https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
#   https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config
#

global:
  scrape_interval: 5s
  scrape_timeout: 10s
  external_labels:
    monitor: 'docker'

scrape_configs:
  - job_name: 'nats'
    static_configs:
      - targets: [ 'nats-exporter:7777' ]
  - job_name: 'rabbitmq'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: [ 'rabbitmq:15672' ]
