version: "3.7"

networks:
  redis: {}
  mongo: {}
  arango: {}
  postgres: {}
  cockroach: {}

volumes:
  redis_data: {}
  mongo_data: {}
  arango_data: {}
  postgres_data: {}
  cockroach_data: {}

services:

  #### DATA BACKENDS

  # https://hub.docker.com/_/redis
  redis:
    image: redis:6.2.5
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis
    volumes:
      - "redis_data:/data"
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  # https://hub.docker.com/_/mongo
  mongo:
    image: mongo:5.0.0
    hostname: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - mongo
    volumes:
      - "mongo_data:/data/db"
      - "./mongo/mongod.conf:/etc/mongo/mongod.conf"
    command: [ "--config", "/etc/mongo/mongod.conf" ]

  # https://hub.docker.com/_/arangodb
  arango:
    image: arangodb:3.7.12
    hostname: arango
    container_name: arango
    restart: always
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=secret
    networks:
      - arango
    volumes:
      - "arango_data:/var/lib/arangodb3"

  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:13.3
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    networks:
      - postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./postgres/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql"

  # https://hub.docker.com/r/cockroachdb/cockroach
  # https://www.cockroachlabs.com/docs/v20.1/start-a-local-cluster-in-docker-linux
  cockroach:
    image: cockroachdb/cockroach:v21.1.6
    hostname: cockroach
    container_name: cockroach
    restart: always
    ports:
      - "8080:8080"
      - "26257:26257"
    networks:
      - cockroach
    volumes:
      - "cockroach_data:/cockroach/cockroach-data"
    command: [ "start", "--insecure" ]
  cockroach-init:
    image: cockroachdb/cockroach:v21.1.6
    hostname: cockroach-init
    container_name: cockroach-init
    depends_on:
      - cockroach
    environment:
      - COCKROACH_HOST=cockroach
    networks:
      - cockroach
    volumes:
      - "./cockroach/init-cockroach.sql:/init/init-cockroach.sql"
    command: [ "shell", "-c", "/cockroach/cockroach.sh sql --insecure < /init/init-cockroach.sql" ]
