#
# Ref:
#   https://prometheus.io/docs/prometheus/latest/configuration/configuration
#   https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config
#   https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
#   https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config
#

global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 10s
  external_labels:
    monitor: 'docker'

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
