# https://www.rabbitmq.com/prometheus.html
# https://github.com/deadtrickster/prometheus_rabbitmq_exporter

FROM rabbitmq:3.8.6-management-alpine

# Install prometheus_rabbitmq_exporter plugin
RUN mkdir -p /usr/lib/rabbitmq/plugins
ADD [ "https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/download/v3.7.2.3/accept-0.3.3.ez", \
      "https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/download/v3.7.2.3/prometheus-3.5.1.ez", \
      "https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/download/v3.7.2.3/prometheus_cowboy-0.1.4.ez", \
      "https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/download/v3.7.2.3/prometheus_httpd-2.1.8.ez", \
      "https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/download/v3.7.2.3/prometheus_process_collector-1.3.1.ez", \
      "https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/download/v3.7.2.3/prometheus_rabbitmq_exporter-3.7.2.3.ez", \
      "/plugins/" ]

RUN chown rabbitmq:rabbitmq /plugins/accept-0.3.3.ez && \
    chmod 644 /plugins/accept-0.3.3.ez && \
    find /plugins/ -name "prometheus*" | xargs -i chown rabbitmq:rabbitmq {} && \
    find /plugins/ -name "prometheus*" | xargs -i chmod 644 {} && \
    rabbitmq-plugins enable prometheus_rabbitmq_exporter
